#!/usr/bin/env bash
# Installing and configuring Nginx

set -e

apt-get update
apt-get install -y nginx

if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sed -i '/server_name _;/a\    add_header X-Served-By $hostname;' \
        /etc/nginx/sites-available/default
fi

nginx -t

service nginx restart
 
