#!/usr/bin/env bash
# Install Nginx and configure a custom X-Served-By HTTP response header

set -e

apt-get update
apt-get install -y nginx

cat > /etc/nginx/sites-available/default <<'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    add_header X-Served-By $hostname;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

nginx -t
service nginx restart
 
